baseURL = 'https://leebee-dev.github.io/'
languageCode = 'ko-kr'
title = '아무것도 모르는 사람이 관리하는 블로그'
theme = 'hugo-theme-m10c'

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[params.social]]
  icon = "brand-github"
  name = "My Github"
  url = "https://github.com/leebee-dev"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"

